# Generated by Django 3.2.13 on 2022-04-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('bid', models.IntegerField(db_column='Bid', primary_key=True, serialize=False)),
                ('bname', models.CharField(blank=True, db_column='Bname', max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'boat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sailor',
            fields=[
                ('sid', models.IntegerField(db_column='Sid', primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, db_column='Sname', max_length=15, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
            ],
            options={
                'db_table': 'sailor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('sid', models.OneToOneField(db_column='Sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='travello.sailor')),
                ('rday', models.DateTimeField(db_column='Rday')),
            ],
            options={
                'db_table': 'reserve',
                'managed': False,
            },
        ),
    ]
